export const SET_POINTS = 'SET_POINTS';
export const SET_CARD = 'SET_CARD';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_TURN = 'SET_TURN';
export const INCREMENT_TURN = 'INCREMENT_TURN';
export const INCREMENT_POINTS = 'INCREMENT_POINTS';
export const DECREMENT_POINTS = 'DECREMENT_POINTS';
