export const SET_COMMAND_POINTS = 'SET_COMMAND_POINTS';
export const SET_VICTORY_POINTS = 'SET_VICTORY_POINTS';
export const SET_LINE_BREAKER = 'SET_LINE_BREAKER';
export const SET_WARLORD = 'SET_WARLORD';
export const SET_FIRST_BLOOD = 'SET_FIRST_BLOOD';
export const INCREMENT_TURN = 'INCREMENT_TURN';
